"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "id" | "en";

interface LanguageContextType {
    lang: Language;
    setLang: (lang: Language) => void;
    t: (key: string) => string;
}

const translations = {
    en: {
        "nav.home": "Home",
        "nav.story": "Our Story",
        "nav.b2b": "B2B Solutions",
        "nav.shop": "Shop",
        "nav.impact": "Impact",
        "nav.collection": "Explore Collection",
        "hero.est": "Est. MMXXVI",
        "hero.bespoke": "Bespoke",
        "hero.circular": "Circular",
        "hero.collection": "The Collection",
        "hero.custom": "Custom Orders",
        "mission.title": "We turn coffee waste into",
        "mission.subtitle": "timeless artifacts.",
        "mission.desc": "A commitment to the circular economy, manifested through high-contrast design and artisanal precision.",
        "mission.discover": "Discover our process →",
        "product.selected": "The Selected",
        "product.showall": "Show All",
        "footer.tagline": "Leading the way in coffee waste transformation and circular economy solutions in Indonesia.",
        "footer.quicklinks": "Quick Links",
        "footer.contact": "Contact",
        "footer.location": "Location",
        "footer.rights": "All Rights Reserved. Crafted with love for the Planet.",
        "shop.title": "Shop Sustainability",
        "shop.subtitle": "Sustainable Goods",
        "shop.desc": "Every purchase supports our mission to reduce coffee waste in Indonesia and heal the Earth.",
        "story.title": "Our Story",
        "story.subtitle": "Giving Coffee a Second Life",
        "story.desc": "From waste to wonder. We breathe new life into discarded coffee grounds through circular innovation.",
        "story.darkside.title": "The Dark Side of Coffee",
        "story.darkside.desc": "Behind every cup of coffee lies a hidden waste problem. Most used coffee grounds end up in landfills, where they decompose anaerobically and release methane gas—contributing significantly to global warming.",
        "story.kopasway.title": "The KOPAS Way",
        "story.kopasway.desc": "KOPAS was born from a simple question: 'How can we give coffee a second life?' We partner with local cafes and hotels to collect their waste, transforming it into beautiful artifacts.",
        "story.step1.title": "Zero-Emission Collection",
        "story.step1.desc": "We partner with local businesses for responsible waste management.",
        "story.step2.title": "Advanced Upcycling",
        "story.step2.desc": "Our techniques ensure every product is durable and high-quality.",
        "story.step3.title": "Circular Loop",
        "story.step3.desc": "The waste returns to the industry as valuable lifestyle assets.",
        "b2b.title": "B2B & Hospitality Solutions",
        "b2b.subtitle": "Eco-Hospitality",
        "b2b.desc": "Elevate your brand with sustainable, circular economy products made from your own coffee waste.",
        "b2b.partner": "Partner with KOPAS",
        "b2b.inquiry": "Send an Inquiry",
        "b2b.inquiry_desc": "Ready to transform your business into a circular one? Let's discuss your custom project.",
        "b2b.service1.title": "Custom Amenities",
        "b2b.service1.desc": "Bespoke soap dishes, toothbrushes, and coasters made from your estate's own coffee waste.",
        "b2b.service2.title": "Sustainable Lobby Art",
        "b2b.service2.desc": "Large-scale architectural panels and decorative pieces for high-end hospitality interiors.",
        "b2b.service3.title": "White Labeling",
        "b2b.service3.desc": "Branded sustainable products for your gift shops and retail outlets.",
        "b2b.form.name": "Full Name",
        "b2b.form.email": "Business Email",
        "b2b.form.company": "Company Name",
        "b2b.form.message": "Your Message",
        "b2b.form.submit": "Submit Inquiry",
        "impact.title": "Sustainability Impact",
        "impact.subtitle": "Collective Effort",
        "impact.desc": "Tracking our collective effort to heal the Earth through coffee waste transformation.",
        "impact.growth": "Waste Diversion Growth",
        "impact.growth_desc": "Our monthly progress in diverting coffee grounds from local Bali cafes and hotels.",
        "impact.stat1": "kg Waste Upcycled",
        "impact.stat2": "kg CO2 Equivalent Prevented",
        "impact.stat3": "Partner Cafes & Hotels",
        "cart.title": "Your Cart",
        "cart.empty": "Your cart is empty",
        "cart.remove": "Remove",
        "cart.checkout": "Checkout Order",
        "cart.whatsapp_msg": "Halo KOPAS! I would like to order:",
        "product.premium": "Premium Selection",
        "product.add": "+ Add",
        "product.candle.name": "Aromatherapy Candle",
        "product.candle.desc": "Soy wax infused with coffee extract. Hand-poured in small batches.",
        "product.shampoo.name": "Shampoo - Coffee Extract",
        "product.shampoo.desc": "Nourishing shampoo made with upcycled coffee antioxidants.",
        "product.conditioner.name": "Conditioner - Moist",
        "product.conditioner.desc": "Deep moisturizing treatment for silky, coffee-scented hair.",
        "product.bodywash.name": "Body Wash - Gentle",
        "product.bodywash.desc": "A gentle formula that cleanses while maintaining skin hydration.",
        "product.aromacubes.name": "Aroma Cubes",
        "product.aromacubes.desc": "The pure scent of freshly ground beans, captured in cube form.",
        "product.coasters.name": "Circular Coaster Set",
        "product.coasters.desc": "Bespoke coasters made from 100% upcycled coffee waste. Water-resistant and heat-durable.",
        "product.lotion.name": "Body Lotion - Nourishing",
        "product.lotion.desc": "Infused with coffee antioxidants to rejuvenate and protect your skin with a luxury scent.",
        "product.hotel_soap.name": "Coffee Craft Soap",
        "product.hotel_soap.desc": "Exfoliating soap bar with repurposed coffee grounds for a smooth, artisanal feel.",
        "admin.panel": "Admin Panel",
        "admin.dashboard": "DASHBOARD",
        "admin.inquiries": "INQUIRIES",
        "admin.orders": "ORDERS",
        "admin.logout": "LOGOUT",
        "admin.loading": "Loading Admin...",
        "admin.login": "Admin Login",
        "admin.restricted": "Restricted Access",
        "admin.authenticating": "AUTHENTICATING...",
        "admin.btn_login": "LOGIN",
        "admin.overview": "Overview",
        "admin.total_inquiries": "Total Inquiries",
        "admin.total_orders": "Total Orders",
        "admin.inquiries_title": "B2B Inquiries",
        "admin.orders_title": "Orders",
        "admin.table.date": "Date",
        "admin.table.company": "Company / Contact",
        "admin.table.msg": "Message",
        "admin.table.loading": "Loading data...",
        "admin.table.no_inq": "No inquiries found.",
        "admin.table.order_date": "Order Date",
        "admin.table.order_id": "Order ID & Status",
        "admin.table.items": "Items",
        "admin.table.total": "Total",
        "admin.table.no_ord": "No orders found.",
        "admin.status.pending": "pending",
        "admin.status.processing": "processing",
        "admin.status.shipped": "shipped",
        "admin.status.completed": "completed",
        "admin.status.cancelled": "cancelled",
    },
    id: {
        "nav.home": "Beranda",
        "nav.story": "Cerita Kami",
        "nav.b2b": "Solusi B2B",
        "nav.shop": "Toko",
        "nav.impact": "Dampak",
        "nav.collection": "Jelajahi Koleksi",
        "hero.est": "Est. MMXXVI",
        "hero.bespoke": "Pesanan",
        "hero.circular": "Sirkular",
        "hero.collection": "Lihat Koleksi",
        "hero.custom": "Pesanan Khusus",
        "mission.title": "Kami mengubah ampas kopi menjadi",
        "mission.subtitle": "artefak abadi.",
        "mission.desc": "Komitmen terhadap ekonomi sirkular, diwujudkan melalui desain kontras tinggi dan presisi artisanal.",
        "mission.discover": "Temukan proses kami →",
        "product.selected": "Pilihan Terpilih",
        "product.showall": "Lihat Semua",
        "footer.tagline": "Memimpin transformasi limbah kopi dan solusi ekonomi sirkular di Indonesia.",
        "footer.quicklinks": "Tautan Cepat",
        "footer.contact": "Kontak",
        "footer.location": "Lokasi",
        "footer.rights": "Hak Cipta Dilindungi. Dibuat dengan cinta untuk Planet.",
        "shop.title": "Belanja Keberlanjutan",
        "shop.subtitle": "Barang Berkelanjutan",
        "shop.desc": "Setiap pembelian mendukung misi kami untuk mengurangi limbah kopi di Indonesia dan menyembuhkan Bumi.",
        "story.title": "Cerita Kami",
        "story.subtitle": "Memberi Kopi Kehidupan Kedua",
        "story.desc": "Dari limbah menjadi keajaiban. Kami menghidupkan kembali ampas kopi yang dibuang melalui inovasi sirkular.",
        "story.darkside.title": "Sisi Gelap Kopi",
        "story.darkside.desc": "Di balik setiap cangkir kopi terdapat masalah limbah yang tersembunyi. Sebagian besar ampas kopi berakhir di tempat pembuangan akhir, di mana mereka terurai secara anaerob dan melepaskan gas metana—berkontribusi signifikan terhadap pemanasan global.",
        "story.kopasway.title": "Cara KOPAS",
        "story.kopasway.desc": "KOPAS lahir dari pertanyaan sederhana: 'Bagaimana kita bisa memberi kopi kehidupan kedua?' Kami bermitra dengan kafe dan hotel lokal untuk mengumpulkan limbah mereka, mengubahnya menjadi artefak yang indah.",
        "story.step1.title": "Pengumpulan Nol Emisi",
        "story.step1.desc": "Kami bermitra dengan bisnis lokal untuk pengelolaan limbah yang bertanggung jawab.",
        "story.step2.title": "Daur Ulang Lanjutan",
        "story.step2.desc": "Teknik kami memastikan setiap produk tahan lama dan berkualitas tinggi.",
        "story.step3.title": "Lingkaran Sirkular",
        "story.step3.desc": "Limbah kembali ke industri sebagai aset gaya hidup yang berharga.",
        "b2b.title": "Solusi B2B & Hospitalitas",
        "b2b.subtitle": "Eco-Hospitalitas",
        "b2b.desc": "Tingkatkan brand Anda dengan produk ekonomi sirkular yang berkelanjutan, dibuat dari limbah kopi Anda sendiri.",
        "b2b.partner": "Bermitra dengan KOPAS",
        "b2b.inquiry": "Kirim Pertanyaan",
        "b2b.inquiry_desc": "Siap mengubah bisnis Anda menjadi sirkular? Mari diskusikan proyek khusus Anda.",
        "b2b.service1.title": "Amenitas Kustom",
        "b2b.service1.desc": "Tempat sabun, sikat gigi, dan tatakan gelas pesanan yang terbuat dari limbah kopi properti Anda sendiri.",
        "b2b.service2.title": "Seni Lobi Berkelanjutan",
        "b2b.service2.desc": "Panel arsitektur skala besar dan potongan dekoratif untuk interior hospitalitas kelas atas.",
        "b2b.service3.title": "White Labeling",
        "b2b.service3.desc": "Produk berkelanjutan bermerek untuk toko suvenir dan gerai ritel Anda.",
        "b2b.form.name": "Nama Lengkap",
        "b2b.form.email": "Email Bisnis",
        "b2b.form.company": "Nama Perusahaan",
        "b2b.form.message": "Pesan Anda",
        "b2b.form.submit": "Kirim Pertanyaan",
        "impact.title": "Dampak Keberlanjutan",
        "impact.subtitle": "Upaya Kolektif",
        "impact.desc": "Melacak upaya kolektif kita untuk menyembuhkan Bumi melalui transformasi limbah kopi.",
        "impact.growth": "Pertumbuhan Pengalihan Limbah",
        "impact.growth_desc": "Kemajuan bulanan kami dalam mengalihkan ampas kopi dari kafe dan hotel lokal di Bali.",
        "impact.stat1": "kg Limbah Didaur Ulang",
        "impact.stat2": "kg Setara CO2 Dicegah",
        "impact.stat3": "Mitra Kafe & Hotel",
        "cart.title": "Keranjang Anda",
        "cart.empty": "Keranjang Anda kosong",
        "cart.remove": "Hapus",
        "cart.checkout": "Selesaikan Pesanan",
        "cart.whatsapp_msg": "Halo KOPAS! Saya ingin memesan:",
        "product.premium": "Pilihan Premium",
        "product.add": "+ Tambah",
        "product.candle.name": "Lilin Aromaterapi",
        "product.candle.desc": "Lilin kedelai dengan ekstrak kopi. Dibuat manual dalam batch kecil.",
        "product.shampoo.name": "Sampo - Ekstrak Kopi",
        "product.shampoo.desc": "Sampo penutrisi dengan antioksidan kopi daur ulang.",
        "product.conditioner.name": "Kondisioner - Moist",
        "product.conditioner.desc": "Perawatan pelembap mendalam untuk rambut halus beraroma kopi.",
        "product.bodywash.name": "Sabun Mandi - Formula Lembut",
        "product.bodywash.desc": "Formula lembut yang membersihkan sekaligus menjaga hidrasi kulit.",
        "product.aromacubes.name": "Aroma Cubes",
        "product.aromacubes.desc": "Aroma murni biji kopi yang baru digiling, dalam bentuk kubus.",
        "product.coasters.name": "Set Tatakan Gelas Sirkular",
        "product.coasters.desc": "Tatakan gelas khusus terbuat dari 100% limbah kopi daur ulang. Tahan air dan tahan panas.",
        "product.lotion.name": "Body Lotion - Menutrisi",
        "product.lotion.desc": "Diperkaya dengan antioksidan kopi untuk meremajakan dan melindungi kulit dengan aroma mewah.",
        "product.hotel_soap.name": "Sabun Kopi Artisanal",
        "product.hotel_soap.desc": "Sabun batang eksfoliasi dengan ampas kopi daur ulang untuk rasa artisanal yang halus.",
        "admin.panel": "Panel Admin",
        "admin.dashboard": "DASBOR",
        "admin.inquiries": "INQUIRY",
        "admin.orders": "PESANAN",
        "admin.logout": "KELUAR",
        "admin.loading": "Memuat Admin...",
        "admin.login": "Login Admin",
        "admin.restricted": "Akses Terbatas",
        "admin.authenticating": "MENGOTENTIKASI...",
        "admin.btn_login": "MASUK",
        "admin.overview": "Ringkasan",
        "admin.total_inquiries": "Total Inquiry",
        "admin.total_orders": "Total Pesanan",
        "admin.inquiries_title": "Inquiry B2B",
        "admin.orders_title": "Pesanan",
        "admin.table.date": "Tanggal",
        "admin.table.company": "Perusahaan / Kontak",
        "admin.table.msg": "Pesan",
        "admin.table.loading": "Memuat data...",
        "admin.table.no_inq": "Belum ada inquiry.",
        "admin.table.order_date": "Tgl Pesanan",
        "admin.table.order_id": "ID Pesanan & Status",
        "admin.table.items": "Item",
        "admin.table.total": "Total",
        "admin.table.no_ord": "Belum ada pesanan.",
        "admin.status.pending": "pending",
        "admin.status.processing": "diproses",
        "admin.status.shipped": "dikirim",
        "admin.status.completed": "selesai",
        "admin.status.cancelled": "dibatalkan",
    }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const [lang, setLang] = useState<Language>("en");

    const t = (key: string) => {
        return translations[lang][key as keyof typeof translations["en"]] || key;
    };

    return (
        <LanguageContext.Provider value={{ lang, setLang, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error("useLanguage must be used within a LanguageProvider");
    }
    return context;
}
